name = "vitor-portfolio"
main = "dist"
compatibility_date = "2024-01-01"

[env.production]
name = "vitor-portfolio-prod"
route = "the-vitor.is-a.dev/*"

[[rules]]
type = "CompiledContentType"
globs = ["**/*.md"]
fallthrough = true
